ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'UTC';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_briefing_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS briefings_enabled BOOLEAN NOT NULL DEFAULT true;
